{% set name = "ctypesgen-pypdfium2-team" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypdfium2-team/ctypesgen/archive/{{ version }}.tar.gz
  sha256: c3709c9faf7d7e8a383714727f86ae6151fc14c28482e1171d7aec518e85387d
  patches:
    - gcc.patch

build:
  entry_points:
    - ctypesgen = ctypesgen.main:main
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python >=3.7

test:
  requires:
    - {{ compiler('c') }}
    - pip
    - pytest  # [linux]
  source_files:  # [linux]
    - run.py  # [linux]
    - tests/  # [linux]
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show ctypesgen
    # run test suite (on linux only)
    - python -m pytest tests/testsuite.py  # [linux]
    # check entry points
    - ctypesgen --help

about:
  home: https://github.com/pypdfium2-team/ctypesgen
  summary: ctypesgen is a ctypes wrapper generator for Python. 
  description: |
    This is a fork with the objective to better suit the needs of pypdfium2, and address some
    of the technical debt and (in our opinion) design issues that have accumulated due to 
    highly conservative maintenance.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
