{% set name = "ctypesgen-pypdfium2-team" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypdfium2-team/ctypesgen/archive/ebd495b1733b60132151154d6358fd1eb336a36a.tar.gz
  sha256: e1598e7be8892427f1ab2e5dba20a58418106676183455078330d2fd018ee411
  patches:
    - gcc.patch

build:
  entry_points:
    - ctypesgen = ctypesgen.__main__:main
  noarch: python
  number: 1
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python >=3.7

test:
  requires:
    - {{ compiler('cxx') }}
    - pip
    - pytest  # [linux]
  source_files:  # [linux]
    - tests/  # [linux]
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show ctypesgen
    # run test suite (on linux only)
    - python -m pytest tests/testsuite.py  # [linux]
    # check entry points
    - ctypesgen --help

about:
  home: https://github.com/pypdfium2-team/ctypesgen
  summary: ctypesgen is a ctypes wrapper generator for Python. 
  description: |
    This is a fork with the objective to better suit the needs of pypdfium2, and address some
    of the technical debt and (in our opinion) design issues that have accumulated due to 
    highly conservative maintenance.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
